config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'staff/index'
  get 'staff/within_radius', to: 'staff#within_radius'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'staff#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/staff_controller.rb
# frozen_string_literal: true

require_relative "../services/process_staff"
class StaffController < ApplicationController
  def index;end;

  def within_radius
    @max = params[:max].to_f || 500.0
    @staff = ProcessStaff.process(@max, Rails.root.join("app","services","staff_list.json").to_s)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OfficeRadius</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div>
    <%= yield %>
    </div>
  </body>
</html>

app/views/staff/index.html.erb
<div class="mx-40" data-controller="staff">
  <%= form_with url: staff_index_path do |form| %>
    <%= form.range_field :max, in: 0..1000, value: 500, data: { action: "input->staff#change" }, class: "w-full h-2 accent-slate-950 rounded-lg my-5" %>
  <% end %>

  <div data-staff-target="list"></div>
</div>

app/views/staff/within_radius.html.erb
<div class="flex justify-center flex-wrap w-full">
  <h1 class="w-full font-sans font-extralight text-4xl text-center my-5">Staff within <span class="font-normal"><%="#{@max.to_i} km"%></span> of the office</h1>
  <div class="flex flex-wrap">
    <% @staff.each do |staff_member| %>
    <div class="rounded shadow-sm border w-100 p-2 m-2">
        <div class="font-bold">
          <%="#{staff_member["name"]}"%>
        </div>
        <div class="font-extralight">
          <%="#{staff_member["role"]}"%>
        </div>
      </div>
    <% end %>
  </div>
</div>